package com.example.pptrefresh.exception;

public enum FailureStage {
    FILENAME_PARSE,
    WHITELIST,
    RULES_LOAD,
    RULES_SCHEMA,
    PRODUCT_NAME_RESOLVE,
    REPORTING_CONTEXT,
    DIMENSION_EXTRACT,
    CONDITION_RESOLVE,
    QUERY_PLAN_BUILD,
    DECK_OPEN,
    TASK_LLM,
    TASK_TOOL,
    TASK_DTO_VALIDATE,
    TASK_RESOLVE_TARGET,
    TASK_WRITE,
    DECK_SAVE,
    UNKNOWN
}
